type notification {
  notification_id: Int!
  notification_type: String!
  name: String!
  message: String!
  time: String!
  profile_pic: String
  reference_id: Int
}

type notifications {
  items: [notification]!
}
input notificationInput {
  notification_ids: [Int!]!
}

union NotificationResponse = notifications

type notificationApiResponse implements apiResponse {
  message: String!
  status: Int!
  success: Boolean!
  error: String
  data: notifications
}

extend type Query {
  getNotification: notificationApiResponse! @auth
}
extend type Mutation {
  seenNotification(input: notificationInput!): notificationApiResponse! @auth
}
